// Code generated by protoc-gen-go-celestinal. DO NOT EDIT.
// Copyright 2025 Duc-Hung Ho

package example

import (
	"fmt"

	"github.com/celestinals/celestinal/api/gen/go/celestinal/v1"
)

var (
	_ celestinal.Empty
)

const ASCII = `
             ______                 
____________ ___  /________         
_  ___/_  _ \__  / __  ___/         CELESTINAL // EXAMPLE
/ /__  /  __/_  /  _(__  )          ------------
\___/  \___/ /_/   /____/           example
                                    
`

// PrintASCII the ASCII art to the console.
func PrintASCII() {
	fmt.Print(ASCII)
}
