// Code generated by protoc-gen-go-tickex. DO NOT EDIT.
// Copyright 2025 Duc-Hung Ho

package example

import (
	"github.com/tickexvn/tickex/api/gen/go/stdx/v1"
)

// StdxOptsOfExampleService_Create get options from service method
func StdxOptsOfExampleService_Create() *stdx.Options {
	options := stdx.Options{}
	options.Roles = []stdx.Role{stdx.Role_ROLE_CUSTOMER}
	return &options
}

// StdxOptsOfExampleService_Delete get options from service method
func StdxOptsOfExampleService_Delete() *stdx.Options {
	options := stdx.Options{}
	options.Roles = []stdx.Role{stdx.Role_ROLE_ADMIN}
	return &options
}
