// Code generated by protoc-gen-go-celestinal. DO NOT EDIT.
// Copyright 2025 Duc-Hung Ho

package example

import (
	"fmt"

	"github.com/celestinals/celestinal/api/gen/go/celestinal/v1"
)

var (
	_ celestinal.Empty
)

const ASCII = `
  _____ ____ ____ ______
 / ___// __// __//_  __/	CELESTINAL // EXAMPLE
/ /__ / _/ _\ \   / /   	-------
\___//___//___/  /_/    	example      

`

// PrintASCII the ASCII art to the console.
func PrintASCII() {
	fmt.Print(ASCII)
}
