services:
  celestinal.redis:
    environment:
      - REDIS_HOST_PASSWORD=

  celestinal.postgres:
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=

  celestinal.edge:
    environment:
      - CELESTINAL_PUBLIC_API_ADDR=
      - CELESTINAL_PUBLIC_TELEGRAM_TOKEN=
      - CELESTINAL_PUBLIC_CHAT_ID=

  celestinal.greeter.v1:
    environment:
      - CELESTINAL_PUBLIC_API_ADDR=
      - CELESTINAL_PUBLIC_TELEGRAM_TOKEN=
      - CELESTINAL_PUBLIC_CHAT_ID=