services:
  celestinal.redis:
    image: redis
    container_name: celestinal.redis
    hostname: celestinal.redis
    ports:
      - "6379:6379"
    command: /bin/sh -c "redis-server --requirepass password"
    volumes:
      - ./_dumpdata/redis:/data
    networks:
      - celestinal-network

  celestinal.postgres:
    image: postgres:latest
    hostname: celestinal.postgres
    container_name: celestinal.postgres
    ports:
      - "5432:5432"
    restart: on-failure:3
    volumes:
      - ./_dumpdata/postgres:/var/lib/postgresql/data
    networks:
      - celestinal-network

  celestinal.consul:
    image: hashicorp/consul:latest
    container_name: celestinal.consul
    hostname: celestinal.consul
    restart: unless-stopped
    ports:
      - "8500:8500"   # UI & API
      - "8600:8600/udp" # DNS
    command: "agent -dev -client=0.0.0.0"
    volumes:
      - ./_dumpdata:/consul/data
    networks:
      - celestinal-network

volumes:
  _dumpdata:

networks:
  celestinal-network:
    driver: bridge