services:
  tickex.edge:
    image: tickexvn/tickex:latest
    ports:
      - "9000:9000"
    networks:
      - tickex-network
    env_file:
      - .env
  tickex.greeter:
    image: tickexvn/tickex.x.greeter:latest
    networks:
      - tickex-network
    env_file:
      - .env

networks:
  tickex-network:
    driver: bridge
