services:
  celestinal.edge:
    container_name: celestinal.apiserver
    hostname: celestinal.apiserver
    image: celestinalvn/celestinal:latest
    ports:
      - "9000:9000"
    networks:
      - celestinal-network

  celestinal.greeter.v1:
    container_name: celestinal.greeter.v1
    hostname: celestinal.greeter.v1
    image: celestinals/celestinal.greeter:latest
    networks:
      - celestinal-network

networks:
  celestinal-network:
    driver: bridge