services:
  tickex.edge:
    container_name: tickex.edge
    hostname: tickex.edge
    image: tickexvn/tickex:latest
    ports:
      - "9000:9000"
    networks:
      - tickex-network

  tickex.x.greeter.v1:
    container_name: tickex.x.greeter.v1
    hostname: tickex.x.greeter.v1
    image: tickexvn/tickex.x.greeter:latest
    networks:
      - tickex-network

networks:
  tickex-network:
    driver: bridge