name: CD / Alpine

on:
  push:
    branches:
      - docker/alpine

jobs:
  publish-tkx-alpine:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry.
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build ./deploy/tkx/alpine -t ghcr.io/tickexvn/tickex/tx.alpine:edge
          docker push ghcr.io/tickexvn/tickex/tx.alpine:edge